### ISSUE TITLE
测试一下

### ISSUE THREAD

**Issue by luckypoem** [lifesinger/blog#238]
看看如何？

**Comment by KIDJourney** [comment]
讲道理你们这些人就不应该用github

**Comment by luckypoem** [comment]
@KIDJourney ,不想对你说粗口。但是不要以为你自己会一点代码，就翘上了天。世界上比你牛的程序员多的是。教你一点做人的道理：“做人要谦虚，不要趾高气扬”，懂吗？搞得github.com好像是你开设的似的，真是笑死人了

**Comment by CodeDaraW** [comment]
@luckypoem 
这里是玉伯前辈的博客repo，在他人的repo提无关的Issue是一种很不礼貌的行为，更何况这是以Issues为博客的repo。而且这个repo有1K+的人Watch了，我们关注这个repo是为了在第一时间收到玉伯前辈博文更新以及大家的讨论，却因为你的一条无意义的测试信息我们都要收到通知，这是在浪费大家的时间。

@所有被这条信息打扰的人，抱歉又给大家增加了一条无用的信息。

**Comment by wujr5** [comment]
@luckypoem  你这样搞得我都取消`watching`了，本来只是想好好关注博客的。很抱歉，又多了一条垃圾回复。
